config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit/destroy your own articles"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :show, :destroy]
  before_action :require_admin_user

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Categroy was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = 'Category was successfully deleted'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin_user
    if logged_in? && !current_user.admin?
      flash[:danger] = "You can't show categories"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:danger] = "You successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = "You only can edit your own profile"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 } )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/views/articles/_article.html.erb
<% articles.each do |a| %>
  <div class="container-card">
    <div class="card card-body bg-light col-6 offset-3">
      <h3><%= link_to a.title, article_path(a), class: 'article_link' %></h3>
      <hr>
      <div class="article_body">
        <%= truncate(a.description, length: 100) %> <br> <br>
        <div class="meta_data alert alert-dark">
        <small>
          Created by: <%= a.user.username %>, <strong><%= time_ago_in_words(a.created_at) %></strong>,
          Time: <strong><%= time_ago_in_words(a.updated_at) %> ago</strong>
        </small>
      </div>
    </div>
    <hr>
    <% if logged_in? && (current_user == a.user || current_user.admin?) %>
      <div class="article_actions">
        <%= link_to 'Edit', edit_article_path(a), class: 'btn btn-info' %>
        <%= link_to 'Show', article_path(a), class: 'btn btn-success' %>
        <%= link_to 'Delete', article_path(a), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container-fluid">
  <%= render 'shared/errors', obj: @article %>
  <div class="row">
    <div class="col-12">
      <%= form_for @article do |a| %>
        <div class="form-group">
          <label>Title</label>
          <%= a.text_field :title, class: 'form-control', placeholder: 'Enter article title', autofocus: true %>
        </div>

        <div class="form-group">
          <label>Description</label>
          <%= a.text_area :description, class: 'form-control', placeholder: 'Enter article description' %>
        </div>

        <%= a.submit class: 'btn btn-primary' %>
        <%= link_to "Back to the articles", articles_path, class: 'btn btn-info' %>

      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container-card col-6 offset-3">
  <h1>Edit Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container-card">
  <div class="col-6 offset-3">
    <%= link_to 'New Article', new_article_path, class: 'btn btn-primary new_article_bottom' %>
  </div>
  <br>
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
</div>

<%= render 'article', articles: @articles %>

<div class="container-card">
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container-card col-6 offset-3">
  <h1>New article</h1>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container-fluid container-card col-6 offset-3">
  <h2 align="center">Title: <%= @article.title %></h2>
  <div class="card card-body bg-light col-xs-8 col-xs-offset-2">
    <div class="text-center">
      <h1><%= @article.user.username %></h1>
      <%= gravatar_for(@article.user, size: 180) %>
    </div>
    <hr>
    <h4 class="center">
      <strong>Description</strong>
    </h4>
    <hr>
    <%= simple_format(@article.description) %>

    <% if logged_in? && (@user == a.user || @user.admin?) %>
      <div class="article_actions">
        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-info' %>
        <%= link_to 'Delete', article_path(@article), method: :delete,
                    data: {confirm: "Are you sure you want to delete this article? "}, class: 'btn btn-danger' %>
        <%= link_to 'All articles', articles_path, class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<% categories.each do |c| %>
  <div class="container-card">
    <div class="card card-body bg-light col-6 offset-3">
      <h3><%= link_to c.name, category_path(c), class: 'category_link' %></h3>
      <hr>
      <% if logged_in? && current_user.admin? %>
        <div class="categories_actions">
          <%= link_to 'Edit', edit_category_path(c), class: 'btn btn-info' %>
          <%= link_to 'Show', category_path(c), class: 'btn btn-success category-show' %>
          <%= link_to 'Delete', category_path(c), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<div class="container-fluid">
  <%= render 'shared/errors', obj: @category %>
  <div class="row">
    <div class="col-12">
      <%= form_for @category do |c| %>
        <div class="form-group">
          <label>Name</label>
          <%= c.text_field :name, class: 'form-control', placeholder: 'Enter category name', autofocus: true %>
        </div>

        <%= c.submit class: 'btn btn-primary' %>
        <%= link_to "Back to the categories", categories_path, class: 'btn btn-info' %>

      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="container-card col-6 offset-3">
  <h1>Edit Category</h1>
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container-card">
  <div class="col-6 offset-3">
    <%= link_to 'New Category', new_category_path, class: 'btn btn-primary new_article_bottom' %>
  </div>
  <br>
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
</div>

<%= render 'category', categories: @categories %>

<div class="container-card">
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container-card col-6 offset-3">
  <h1>New Category</h1>
  <%= render 'form' %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <small class="footer-copyright">
      Copyright &copy; <a href="https://www.udemy.com" class="footer-link">The Complete Ruby on Rails Developer</a>
      by <a href="http://www.abrahanmendoza.com" class="footer-link">Abrahan Mendoza</a>
    </small>

    <small class="footer-links">
      <%= link_to 'About', pages_about_path, class: 'footer-item' %>
    </small>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> alert-div alert-dismissible fade show" role="alert">
    <p><%= msg %></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: 'nav-link' %>
      </li>
      <% if logged_in? %>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Categories', categories_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New Article', new_article_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'View users', users_path, class: 'dropdown-item' %>
          </div>
        </li>
      <% end %>
    </ul>

    <!--    <form class="form-inline my-2 my-lg-0">-->
    <!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
    <!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
    <!--    </form>-->
    <% if logged_in? %>
      <ul class="navbar-nav profile_dropdown_user">
        <% if logged_in? && current_user %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <a href="#" class="nav-link">Admin</a>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to current_user.email, user_path(current_user), class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Update profile', edit_user_path(current_user), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'View profile', user_path(current_user), class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
      <%= link_to 'Log out', logout_path, method: :delete, class: 'btn btn-danger logout-btn' %>
    <% else %>
      <%= link_to 'Login', login_path, class: 'btn btn-primary login-btn' %>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alpha Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="page-container">
  <div class="content-wrap">
    <%= render 'layouts/navigation' %>
    <div class="container-fluid">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>

  <% if Rails.env.development? %>
    <div class="alert alert-success" role="alert">
      <%= debug(params) %>
    </div>
  <% end %>
</div>
</body>

</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<%= link_to 'Home', pages_home_path %>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1 class="display-4">Alpha Blog</h1>
  <p class="lead">This is our rails blog, you can write your own things</p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to 'Sign Up', signup_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">The following errors prevented the article from getting created</h4>
        <div class="panel-body">
          <%= pluralize(obj.errors.count, "error") %>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container-fluid col-6 offset-3 signup_user">
  <%= render 'shared/errors', obj: @user %>
  <div class="row">
    <div class="col-12">

      <h1 class="text-center"><%= user_form_title %></h1>

      <%= form_for(@user, :html => { role: 'form'}) do |u| %>

        <div class="form-group">
          <label>Username</label>
          <%= u.text_field :username, class: 'form-control', placeholder: 'Enter username', autofocus: true %>
        </div>

        <div class="form-group">
          <label>Email</label>
          <%= u.email_field :email, class: 'form-control', placeholder: 'Enter email', autofocus: true %>
        </div>

        <div class="form-group">
          <label>Password</label>
          <%= u.password_field :password, class: 'form-control', placeholder: 'Enter password' %>
        </div>

        <%= u.submit submit_button, class: 'btn btn-primary' %>

      <% end %>
    </div>
  </div>
</div>

app/views/users/all_users.html.erb
<div class="container-fluid text-center col-6 offset-3">
  <br> <h1>All Alpha bloggers</h1> <br>
  <% @users.each do |user| %>
    <br>
    <div class="card">
      <%= gravatar_for(user, size: 180) %>
      <div class="card-body">
        <h5 class="card-title"><%= user.username %></h5>
        <small class="card-title"><%= pluralize(user.articles.count, "article") %></small> <br> <br>
        <%= link_to 'Show user', user_path(user), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'users/form', user_form_title: "Update your account", submit_button: 'Update' %>

app/views/users/index.html.erb
<div class="container-fluid text-center col-6 offset-3">
  <br> <h1>All Alpha bloggers</h1> <br>
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <% @users.each do |user| %>
    <br>
    <div class="card">
      <%#= gravatar_for(user, size: 180) %>
      <div class="card-body">
        <h5 class="card-title"><%= user.username %></h5>
        <small class="card-title"><%= pluralize(user.articles.count, "article") %></small> <br> <br>
        <%= link_to 'Show user', user_path(user), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
  <br>
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'users/form', user_form_title: "Sign Up", submit_button: 'Sign Up' %>

app/views/users/show.html.erb
<div class="container-fluid container-card col-6 offset-3 text-center">
  <br> <h1>Welcome to <%= @user.username %>'s page</h1> <br>
  <div class="user_profile">
    <%= gravatar_for @user %>
  </div>
  <br>
  <h4><%= @user.username %>'s articles</h4>
  <%= link_to 'Update my profile', edit_user_path(@user), class: 'btn btn-info' if current_user == @user %>
</div>

<div class="container-fluid container-card text-center">
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
  <%= render 'articles/article', articles: @articles %>
  <br>
  <div class="col-6 offset-3 pagination">
    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
  </div>
</div>